build:
    stage: build
    before_script:
        - apt-get update -y 
        - apt-get install -y make libglib2.0-bin zip unzip
    script: make
    artifacts:
        paths: 
            - MarantzDenon_AVR_controller@seifattar.net.zip
        expire_in: 1 day
